apiVersion: v1
kind: Pod
metadata:
  name: labeled-pod
  labels:
    app: my-app
    environment: production
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
